FROM nginx:stable-alpine

# Supprime la config par défaut
RUN rm /etc/nginx/conf.d/default.conf

# config Nginx
COPY site.conf /etc/nginx/conf.d/default.conf

# Fichiers static frontend
COPY app/static /var/www/html/

EXPOSE 80
EXPOSE 443